// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2cXHNd_IHQqS_HMLyuUOyOeNDIzB32h4',
    appId: '1:3052507089:web:cef06bf896d901ec8adaf0',
    messagingSenderId: '3052507089',
    projectId: 'sportappewa',
    authDomain: 'sportappewa.firebaseapp.com',
    storageBucket: 'sportappewa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoLJ4-E-HFnpS9xQjbTMgOPxQt-Kv8u_Q',
    appId: '1:3052507089:android:92460efc64af2bc28adaf0',
    messagingSenderId: '3052507089',
    projectId: 'sportappewa',
    storageBucket: 'sportappewa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYTd3PvFFIVfIZtD2y7K5SA8ABbodXDbA',
    appId: '1:3052507089:ios:d4dcf583321431758adaf0',
    messagingSenderId: '3052507089',
    projectId: 'sportappewa',
    storageBucket: 'sportappewa.appspot.com',
    iosClientId:
        '3052507089-8qf86g60d4gk9pnhra9ppkrqfufph0u1.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportAppEwa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYTd3PvFFIVfIZtD2y7K5SA8ABbodXDbA',
    appId: '1:3052507089:ios:5fd1aeb74ff4f90d8adaf0',
    messagingSenderId: '3052507089',
    projectId: 'sportappewa',
    storageBucket: 'sportappewa.appspot.com',
    iosClientId:
        '3052507089-cojd9eiq0mtc40brvdkqd92g3fpdv2hc.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportAppEwa.RunnerTests',
  );
}
