name: sport_app_ewa
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  dio: ^5.4.2+1
  firebase_auth: ^4.18.0
  firebase_core: ^2.27.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  google_sign_in: ^6.2.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.2
  share_plus: ^8.0.3
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
